jobs:
  build_jar:
    name: Build Jar
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Set Version
      uses: datamonsters/replace-action@v2
      with:
        files: pom.xml
        replacements: Snapshot=${{ github.event.inputs.version_number }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - continue-on-error: true
      name: Rename jar
      run: mv target/*-All.jar JMusicBot-${{ github.event.inputs.version_number }}.jar
    - continue-on-error: true
      name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: jar
        path: JMusicBot-${{ github.event.inputs.version_number }}.jar
  create_release:
    name: Create Release
    needs: build_jar
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: jar
        path: .
    - continue-on-error: true
      name: Show Artifacts
      run: ls -R
    - continue-on-error: true
      name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '*.jar'
        body: "${{ github.event.inputs.info }}\n\n---\n### Setup\nhttps://jmusicbot.com/setup\
          \  \nhttps://jmusicbot.com/config  \n# Download: [JMusicBot-${{ github.event.inputs.version_number\
          \ }}.jar](https://github.com/jagrosh/MusicBot/releases/download/${{ github.event.inputs.version_number\
          \ }}/JMusicBot-${{ github.event.inputs.version_number }}.jar)\n"
        draft: true
        name: Version ${{ github.event.inputs.version_number }}
        prerelease: false
        tag: ${{ github.event.inputs.version_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: Make Release
on:
  repository_dispatch:
    types: trigger-ga___make-release.yml
